<html itemscope="" itemtype="http://schema.org/WebSite" prefix="og: http://ogp.me/ns#" class="no-js" dir="ltr" lang="en-GB"><head>
    <meta charset="utf-8">
    <meta name="Content-Type" content="text/html;charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, initial-scale=1.0, user-scalable=no">
    <meta name="format-detection" content="telephone=no">


    <title>This website is down for maintenance; please try again later</title>
	<?php $cdn_url='https://cdn.trackbniconnect.com';?>
	
	<?php $cdn_url='https://cdn.trackbniconnect.com';?>
    <meta name="title" content="BNI: Changing the Way the World Does Business®">
    <meta name="keywords" content="BNI, Business Networking, Referrals">
    <meta name="description" content="Founded in 1985, BNI® is a global, proven business networking organization.">

    <meta name="creation_date" content="2018-01-02 12:00:16">
    <meta name="robots" content="INDEX,FOLLOW">
    <meta name="author" content="BNI">

    <link rel="shortcut icon" href="<?= $cdn_url; ?>/appicon/favicon.ico" type="image/ico">
    <link rel="shortcut icon" href="<?= $cdn_url; ?>/appicon/favicon.png" type="image/x-icon">

    <!-- Apple mobile icons -->
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-57x57.png" sizes="57x57">
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-60x60.png" sizes="60x60">
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-72x72.png" sizes="72x72">
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-76x76.png" sizes="76x76">
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-114x114.png" sizes="114x114">
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-120x120.png" sizes="120x120">
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-128x128.png" sizes="128x128">
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-144x144.png" sizes="144x144">
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-152x152.png" sizes="152x152">
    <link rel="apple-touch-icon" href="<?= $cdn_url; ?>/appicon/icon-180x180.png" sizes="180x180">

    <!-- iOS mobile icons and colors -->
    <meta name="theme-color" content="#FFFFFF">
    <link rel="icon" type="image/png" sizes="36x36" href="<?= $cdn_url; ?>/appicon/icon-36x36.png">
    <link rel="icon" type="image/png" sizes="48x48" href="<?= $cdn_url; ?>/appicon/icon-48x48.png">
    <link rel="icon" type="image/png" sizes="72x72" href="<?= $cdn_url; ?>/appicon/icon-72x72.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?= $cdn_url; ?>/appicon/icon-96x96.png">
    <link rel="icon" type="image/png" sizes="148x148" href="<?= $cdn_url; ?>/appicon/icon-144x144.png">
    <link rel="icon" type="image/png" sizes="192x192" href="<?= $cdn_url; ?>/appicon/icon-192x192.png">

    <!-- Android mobile icons -->
    <link rel="icon" type="image/png" sizes="16x16" href="<?= $cdn_url; ?>/appicon/icon-16x16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?= $cdn_url; ?>/appicon/icon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?= $cdn_url; ?>/appicon/icon-96x96.png">
    <link rel="icon" type="image/png" sizes="128x128" href="<?= $cdn_url; ?>/appicon/icon-128x128.png">

    <!-- Windows mobile icons and colors -->
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="<?= $cdn_url; ?>/appicon/icon-144x144.png">

    <link rel="canonical" href="http://mjsey.com/en_GB/index">

    <!-- Open Graph meta tags -->
    <meta property="og:site_name" content="mjsey">
    <meta property="og:title" content="Home">
    <meta property="og:description" content="Founded in 1985, BNI® is a global, proven business networking organization.">
    <meta property="og:url" content="http://mjsey.com/en_GB/index">
    <meta property="og:image" content="<?= $cdn_url; ?>/appicon/socialmedia.png">
    <!-- Twitter card meta tags -->
    <meta name="twitter:card" content="summary">
    <meta name="twitter:url" content="http://mjsey.com/en_GB/index">
    <meta name="twitter:title" content="Home">
    <meta name="twitter:description" content="Founded in 1985, BNI® is a global, proven business networking organization.">
    <meta name="twitter:image" content="<?php echo $this->config->general->cdn; ?>/new_template/assets/appicon/socialmedia.png">


    <meta itemprop="image" content="<?php echo $cdn_url; ?>/new_template/assets/appicon/socialmedia.png">

   <link rel="shortcut icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/favicon.ico" type="image/ico">
	<link rel="shortcut icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/favicon.png" type="image/x-icon">

<!-- Apple mobile icons -->
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-57x57.png" sizes="57x57">
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-60x60.png" sizes="60x60">
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-72x72.png" sizes="72x72">
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-76x76.png" sizes="76x76">
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-114x114.png" sizes="114x114">
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-120x120.png" sizes="120x120">
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-128x128.png" sizes="128x128">
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-144x144.png" sizes="144x144">
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-152x152.png" sizes="152x152">
    <link rel="apple-touch-icon" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-180x180.png" sizes="180x180">
	
	<!-- iOS mobile icons and colors -->
    <meta name="theme-color" content="#FFFFFF">
    <link rel="icon" type="image/png" sizes="36x36" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-36x36.png">
    <link rel="icon" type="image/png" sizes="48x48" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-48x48.png">
    <link rel="icon" type="image/png" sizes="72x72" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-72x72.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-96x96.png">
    <link rel="icon" type="image/png" sizes="148x148" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-144x144.png">
    <link rel="icon" type="image/png" sizes="192x192" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-192x192.png">

<!-- Android mobile icons -->
    <link rel="icon" type="image/png" sizes="16x16" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-16x16.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-96x96.png">
    <link rel="icon" type="image/png" sizes="128x128" href="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-128x128.png">   

	 <!-- Windows mobile icons and colors -->
    <meta name="msapplication-TileColor" content="#FFFFFF">
    <meta name="msapplication-TileImage" content="<?php echo $cdn_url; ?>/new_template/assets/appicon/icon-144x144.png">

    <link rel="canonical" href="http://mjsey.com/en_GB/index">	

    <script type="application/ld+json">
    {
      "@context": "http://www.schema.org",
      "@type": "Organization",
      "name": "mjsey",
      "url": "http://mjsey.com/en_GB/index",
      "logo": "<?= $cdn_url; ?>/new_template/assets/appicon/socialmedia.png",
      "image": "<?= $cdn_url; ?>/new_template/assets/appicon/socialmedia.png",
      "description": "Founded in 1985, BNI® is a global, proven business networking organization.",
      "address": {
        "@type": "PostalAddress",
        "streetAddress": "",
        "addressLocality": "",
        "addressRegion": "",
        "postalCode": "",
        "addressCountry": ""
      },
      "contactPoint": {
        "@type": "ContactPoint",
        "telephone": "",
        "ContactType": "customer support"
      }
    }
    </script>
	
	 <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/libs/jquery-ui-1.12.1.custom/jquery-ui.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/libs/bootstrap-3.3.7-dist/css/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/libs/jquery.mmenu-6.1.0/jquery.mmenu.all.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/libs/fancybox-master-3.1.20/dist/jquery.fancybox.min.css">

    <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/libs/fullcalendar-3.4.0/fullcalendar.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/libs/fullcalendar-3.4.0/fullcalendar.print.css" media="print">

    <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/libs/DataTables-1.10.15/Responsive-2.1.1/css/responsive.bootstrap.min.css">
    
    <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/libs/font-awesome-4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/libs/bni-font-icon-4.0/style.css">

    <link rel="stylesheet" type="text/css" href="<?php echo $cdn_url; ?>/new_template/assets/styles/css/styles-ltr.css">

<!-- JS Files -->
    <script src="<?php echo $cdn_url; ?>/new_template/libs/fullcalendar-3.4.0/lib/moment.min.js"></script>

    <script src="<?php echo $cdn_url; ?>/new_template/libs/jquery-3.2.1/jquery-3.2.1.min.js"></script>
    <script src="<?php echo $cdn_url; ?>/new_template/libs/jquery-ui-1.12.1.custom/jquery-ui.min.js"></script>

    <script src="<?php echo $cdn_url; ?>/new_template/libs/jquery-validation-1.16.0/dist/jquery.validate.min.js"></script>
    <script src="<?php echo $cdn_url; ?>/new_template/libs/jquery-validation-1.16.0/dist/additional-methods.min.js"></script>
    <script src="<?php echo $cdn_url; ?>/new_template/libs/jquery-validation-1.16.0/lib/jquery.form.min.js"></script>

    <script src="<?php echo $cdn_url; ?>/new_template/libs/jquery-3.2.1/jquery.touchSwipe.min.js"></script>
    <script src="<?php echo $cdn_url; ?>/new_template/libs/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
    <script src="<?php echo $cdn_url; ?>/new_template/libs/jquery.mmenu-6.1.0/jquery.mmenu.all.js"></script>

    <script src="<?php echo $cdn_url; ?>/new_template/libs/fancybox-master-3.1.20/dist/jquery.fancybox.min.js"></script>

    <script src="<?php echo $cdn_url; ?>/new_template/libs/fullcalendar-3.4.0/fullcalendar.min.js"></script>

    <script src="<?php echo $cdn_url; ?>/new_template/libs/DataTables-1.10.15/datatables.min.js"></script>
    <script src="<?php echo $cdn_url; ?>/new_template/libs/DataTables-1.10.15/Responsive-2.1.1/js/responsive.bootstrap.min.js"></script>

    <script src="<?php echo $cdn_url; ?>/new_template/assets/scripts/common.js"></script>
  

</head>
<body class="pc">

<div class="page mm-page mm-slideout" id="mm-0">
    <!-- HEADER WIDGET -->
    <header>
        <div class="row bottomRow">
            <div class="holder">
                <div class="col-xs-10 col-sm-9 col-md-12 col-lg-6 colLogo">
                    <a class="bniLogo" href="#">
                        <span class="ico-068"></span>
                        <span class="texts">
                                <span class="name"> CMS </span>
                                <span class="tagline">Local Business - Global Network ®</span>
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </header>

    <section class="widgetPageHeader">
        <div class="holder">
            <div class="col-xs-12 col-sm-6 col-md-6">
                <h1>Down for maintenance <i class="fa fa-wrench" aria-hidden="true"></i></h1>
            </div>
        </div>
    </section>

    <section class="widgetTextColumns">
        <div class="holder">
            <div class="wysiwyg">
                <p>This website is currently down for maintenance. Please try again later</p>
            </div>
        </div>
    </section>

    <footer>
        <div class="copyrightRow">
            <div class="holder">
                <div class="col-xs-12">
                    <p><strong>© 2018 BNI Global LLC.</strong>  All Rights Reserved. All company names, product names logos included here may be registered trademarks or service marks of their respective owners.</p>
                </div>
            </div>
        </div>
    </footer>
</div>
