<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Image Selector</title>

    <!-- Bootstrap -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- ROBOTO FONT -->
    <link rel="stylesheet" type="text/css" href="<?php echo $this->config->general->cdn; ?>/roboto-font/roboto.css">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/bnicms/v3/css/AdminLTE.css">
    <link rel="stylesheet" type="text/css" href="/bnicms/v3/css/skin-red.css">
    <link rel="stylesheet" type="text/css" href="/bnicms/v3/css/ionicons.css">
    <link rel="stylesheet" type="text/css" href="/bnicms/v3/css/theme.css">
    <link rel="stylesheet" type="text/css" href="/bnicms/v3/css/dataTables.bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/bnicms/v3/css/AdminLTE.min.css.css">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="<?php echo $this->config->general->cdn; ?>/bni-font-icon-3.0/style.css">

    <!-- Latest compiled and minified JavaScript -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script src="https://cdn.ckeditor.com/4.7.2/standard/ckeditor.js"></script>
    <style>.cke {
            visibility: hidden;
        }</style>

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"
            integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>


    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

    <script src="/bnicms/v3/js/modalClose/listener.js"></script>

    <script src="/bnicms/v3/js/submitModal.js" async></script>

    <script type="text/javascript" src="/bnicms/v3/js/adminlte.min.js" async></script>
    <script type="text/javascript" src="/bnicms/v3/js/dataTables.bootstrap.min.js" async></script>
    <script type="text/javascript" src="/bnicms/v3/js/dateformat.js"></script>
    <script type="text/javascript" src="<?php echo $this->config->general->cdn; ?>/js/common.min.js"></script>
    <script type="text/javascript"
            src="<?php echo $this->config->general->cdn; ?>/bundles/jquery.mmenu-6.1.0/jquery.mmenu.all.js"></script>

</head>

<body>

<?php
echo $this->getContent();
?>

</body>
</html>
