<script src="/bnicms/v3/js/modalClose/closeModal.js"></script>
<div class="container">
    <?= $this->getContent(); ?>
    <?php
    if(count($availableLanguages)>0){?>
    <div class="row">
        <div class="col-md-12">
            <form method="post">
                <div class="form-group">
                    <label for="languageValue"><?= $this->translator->_('cms.v3.admin.languages.newlanguagemsg'); ?></label>
                    <select multiple class="form-control" name="languageValue[]" id="languageValue">
                        <?php
                        foreach ($availableLanguages as $availableLanguage) {?>

                            <option value="<?= $availableLanguage->id ?>"><?= $availableLanguage->token ?></option>
                            <?php
                        }
                        ?>
                    </select>
                </div>
                <div class="form-group">
                    <label for="statusValue"><?= $this->translator->_('cms.v3.admin.languages.status'); ?></label>
                    <select class="form-control" name="statusValue" id="settingValue">
                        <option value="2"><?= $this->translator->_('cms.v3.admin.languages.disabled'); ?></option>
                        <option value="1"><?= $this->translator->_('cms.v3.admin.languages.enabled'); ?></option>
                    </select>
                </div>
            </form>
        </div>
    </div>
    <?php
    }else{?>
        <div class="alert alert-warning" role="alert">
            <strong><?= $this->translator->_('cms.v3.admin.languages.allsupportedlangsmsg'); ?></strong>
        </div>
    <?php }?>
</div>

<script>
    // When the document is ready, check on intervals if the success alert is on display.
    // If the success alert is on display then this means we've successfully completed our action and we can close the form
    // Close modal function is highly specific to the bootstrap modal and expects some sort of successful alert in this file to process
    $(document).ready(function(){
        closeModal('#addLanguagesModal');
    });
</script>