<section class="widgetChapterHomeDetail">
    <div class="holder">
        <?php
		if($partial_domain=="defaultchapter") error_reporting(0);
		
        $phone = $mappedWidgetSettings->getValueByName("Phone");
        $directions = $mappedWidgetSettings->getValueByName("Directions");
        $memberCount =  $mappedWidgetSettings->getValueByName("Member Count");
        $showMembers = $mappedWidgetSettings->getValueByName("Show Members");
        $chapterSpeakers = $mappedWidgetSettings->getValueByName("Chapter Speakers");
        $doesRegionAllowOnlineApplicationsCheck = !isset($jsonForOnlineApplicationsCheck) ?  "" : $jsonForOnlineApplicationsCheck->{'cancreate'};
        ?>

        <div class="rowDetail">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 firstCol">
                <h2><?php echo $ChapterDetails['name']; ?></h2>
                <p><?php echo $ChapterDetails['chapterText'] ?> </p>
            </div>
        </div>
        <br>
        <div class="rowDetail">
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 firstCol">
                <h3><?= $mappedWidgetSettings->getValueByName("Meeting Details") ?></h3>
                <p class="meetingDate"><?php echo $OrgType != "PLANNED_CHAPTER" && isset($ChapterDetails['meetingDay']) && isset($ChapterDetails['meetingTime']) ? $ChapterDetails['meetingDay'] . ' ' . $ChapterDetails['meetingTime'] : '' ?></p>
				<?php if(($OrgType != "PLANNED_CHAPTER")&&isset($ChapterDetails['meetingTypeText'])):?>
				<p><?php echo $ChapterDetails['meetingTypeText'];?></p>
				<?php endif;?>
                <p><strong><?php echo $ChapterDetails['locationName']; ?></strong></p>
                <p class="address"><?php echo $ChapterDetails['addressLine1']; ?>
                    <?php if(isset($ChapterDetails['addressLine2']) && !empty($ChapterDetails['addressLine2'])) {
                        echo "<br>".$ChapterDetails['addressLine2'];
                    } ?>
                    <br><?php echo $ChapterDetails['city']; ?>
                    <br><?php echo isset($ChapterDetails['state']) ? $ChapterDetails['state'] : ''; ?>
                    <br><?php echo $ChapterDetails['postalCode']; ?></p>
                <p class="-phone"><bdi><?php echo isset($ChapterDetails['phoneNumber']) && !empty($ChapterDetails['phoneNumber']) ? "<strong>" . $phone . ": </strong>" . $ChapterDetails['phoneNumber'] : "" ?></bdi></p>

                <?php if (!empty($ChapterDetails['mapUrl'])) {
                    $fixedUrl = substr($ChapterDetails['mapUrl'], 0, 4) === "http" ? $ChapterDetails['mapUrl'] : 'http://' . $ChapterDetails['mapUrl']; ?>
                    <p><?php echo isset($ChapterDetails['directions']) && !empty($ChapterDetails['directions']) ? "<strong>" . $directions . ": </strong>" . $ChapterDetails['directions'] : "" ?></p>

                    <p><a href="<?php echo $fixedUrl; ?>"
                          target="_blank"><?= $mappedWidgetSettings->getValueByName("View Map")?></a>
                    </p>
                <?php } ?>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 secondCol">
                <h3><?php echo $memberCount; ?></h3>
				<?php 
					if($MemberListVal=="on"):?>
					<a href="<?php echo $memberListLink; ?>?chapterName=<?= $chapterId ?>&regionIds=<?= $regionId ?>$isChapterwebsite"
                   class="numberLink">
				<?php 
					else: 
						echo '<span class="numberLink">';
					endif;
				?>	      
				   <?=$OrgMemberCount?>
				   <?php if($MemberListVal=="on"):?>
						<span><?php echo $showMembers; ?></span></a>
					<?php 
					else:
						echo '</span>';
					endif;
					?>	
            </div>

            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 thirdCol">
                <?php
                $visitorRegUrl = ($useLatestCode == true ? "visitorregistration?chapterId=" . $chapterId :  $ChapterDetails['visitChapterUrl']);
                ?>
                <a href="<?php echo $visitorRegUrl; ?>"
                   target="_blank"
                   class="button"><?php echo $mappedWidgetSettings->getValueByName("Visit Us!") ?>
                    <span class="ico-048"></span></a>
            </div>
            <?php
            if (count($chapterWebsiteAndGalleryArray) > 1) {
                $website = $chapterWebsiteAndGalleryArray[0];
                ?>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 thirdCol">
                    <?php
                    $renderStaticContent = $renderStaticContent === 'true' ? true : false;

                    $url = $renderStaticContent ?
                        "http://" . $this->websiteHelper->strip_accents($website->clean_domain) . "/" . $this->translationUtils->normalizeLocaleCode($chapterWebsiteAndGalleryArray[2],false) . "/" . $chapterWebsiteAndGalleryArray[1]
                        : $this->url->get("backend/render/preview/" . $this->websiteHelper->strip_accents($website->clean_domain) . "/" . $this->translationUtils->normalizeLocaleCode($chapterWebsiteAndGalleryArray[2],false) . "/" . $chapterWebsiteAndGalleryArray[1]); ?>
                    <a href="<?php echo $url ?>"
                       target="_self"
                       class="button"><?php echo $mappedWidgetSettings->getValueByName("View Gallery") ?>
                        <span class="ico-048"></span>
                    </a>
                </div>
                <?php
            }
            ?>

            <!-- Apply Now button -->
            <?php
            $applicantRegUrl = ($useLatestCode == true ? "applicationregistration?chapterId=" . $chapterId :  $ChapterDetails['visitChapterUrl']);
            ?>
            <?php if ($OrgType != "PLANNED_CHAPTER" && $doesRegionAllowOnlineApplicationsCheck == true) {
				if($OnlineApplications=="on"):?>
                <div class="col-xs-12 col-sm-6 col-md-4 col-lg-4 thirdCol"><a
                            href="<?php echo $applicantRegUrl; ?>"
                            target="_self"
                            class="button"><?= $mappedWidgetSettings->getValueByName("Apply Now") ?>
                        <span class="ico-048"></span></a>
                </div>

            <?php
				endif;
			} ?>


        </div>
	</div>
</section>	

<section class="widgetChapterHomeDetail">
    <div class="holder">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <?php
        if (count($jsonData) > 0) {
        ?>
        <div class="chapterSpeakerRow">

            <h2><?= $chapterSpeakers ?></h2>
            <?php
            foreach ($jsonData as $speaker) {
                ?>
                <p><span class="date"> <?= $speaker->meetingDate ?></span><span
                            class="name"> <?= $speaker->speakerName ?></span> <?= $speaker->speakerTopic ?></p>
                <?php
            }

            }
            ?>
				</div>
			
		</div>
	</div>
</section>	

<?php if ((count($LeadershipTeam) >0 && !empty($LeadershipTeam))&&($ChapterLeadershipVal=="on")){ ?>        
<section class="widget_chapterdetails_people">
            <div class="holder">
                <div class="leadership-taholder">
                    <ul class="nav nav-tabs leadership_tab" id="myTab" role="tablist">
                        <?php if ((count($LeadershipTeam) >0 && !empty($LeadershipTeam))&&($ChapterLeadershipVal=="on")){ ?>
						<li class="nav-item active">
                            <a class="nav-link active" id="chapter_leaders_tab" data-toggle="tab" href="#Chapter_leaders" role="tab" aria-controls="<?= $mappedWidgetSettings->getValueByName("Chapter Leadership") ?>" aria-selected="true">
							<? echo $this->translator->_('cms.v3.admin.chapterdetails.chapterleadership'); ?></a>
							</a>
                        </li>
						<?php } ?>
                        
                    </ul>
                    <div class="tab-content chapter_leaders_tab_content" id="myTabContent">
                        <div class="tab-pane fade active in" id="Chapter_leaders" role="tabpanel" aria-labelledby="chapter_leaders_tab">
                            
							<?php if ((count($LeadershipTeam) >0 && !empty($LeadershipTeam))&&($ChapterLeadershipVal=="on")){
								//print"<pre>";print_r($leadershipRole);print"</pre>";
								?>
							<?php if(isset($leadershipRole['president'])&&(count($leadershipRole['president']) >0 && !empty($leadershipRole['president']))):?>		
							<div class="chptr_leadr_card_row">
								<?php foreach($leadershipRole['president'] as $ps):
										$name = $ps['firstName'] . ' ' . $ps['lastName']; 
										if($ps['companyName']!=""):
											$companyName=$ps['companyName'];
										else:
											$companyName=$ps['companyWebsitelink'];
										endif;
										
										if($ps['profileImageUrl']!=""):
											$profile_img=$ps['profileImageUrl'];
										else:
											$profile_img=$this->config->general->cdn.'/new_template/assets/images/default.svg';
										endif;
										
										$website_link='javascript:;';
										if($ps['companyWebsitelink']!=""):
											$website_link=$ps['companyWebsitelink'];
											$website_link=parse_url($website_link, PHP_URL_SCHEME)==''?'http://'.$website_link:$website_link;
										endif;
										
								?>
                                <div class="leader_headwrap">
                                    <p><?php echo $ps['role']; ?></p>
                                    <div class="leaders_card_holder">
                                        <div class="profile_picture">
                                            <img src="<?php echo $profile_img;?>" alt="default">
                                        </div>
                                        <div class="leadership_card_content_holder">
                                            <h4 title="<?php echo $name;?>"><?php echo $name; ?></h4>
                                            <h5 title="<?php echo $ps['role'];?>"><?php echo $ps['role']; ?></h5>
                                            <p class="company_name"><a <?php if($website_link!="javascript:;"){?> href="<?php echo $website_link; ?>"  target="_blank" <?php }else{echo 'class="leadership_withoutwebsite"';} ?> title="<?php echo $companyName; ?>"><?php if($companyName!=""): echo $companyName; else: echo '&nbsp;'; endif; ?></a></p>
                                            <div class="mail_call_profile_viewholder">
                                                <div class="leftside">
													<?php if(!is_null($ps['phone'])&&($ps['phone']!="")):?>
                                                    <a href="tel:<?php echo $ps['phone']; ?>"><i class="fa fa-phone" aria-hidden="true"></i></a>
                                                    <?php endif; 
													if(!is_null($ps['email'])&&($ps['email']!="")):?>
													<a href="<?php echo 'sendmessage?userId=' . $this->securityUtils->encryptUrlEncoded($ps['userId']) . '&userName=' . urlencode($name) ?>"
													   target="_self" class="iconEmail"><i class="fa fa-envelope-o"  data-toggle='tooltip' title='<?php echo $this->translator->_('cms.v3.admin.editpage.sendmessage')?>' aria-hidden="true"></i></a>
													<?php endif;?>
                                                </div>
												<?php if(!is_null($ps['cmsProfileUrl'])&&($ps['cmsProfileUrl']!="N/A")):
														$cmsProfileUrl=$ps['cmsProfileUrl'];
														if (strpos($cmsProfileUrl, 'memberdetails') !== false):
															$member_url=explode('memberdetails',$cmsProfileUrl);
															$cmsProfileUrl='memberdetails'.$member_url[1];
														endif;
												?>
													<div class="right_side">
														<a href="<?php echo $cmsProfileUrl;?>"><? echo $this->translator->_('cms.v3.admin.chapterdetails.viewprofile'); ?>  <i class="fa fa-angle-right" aria-hidden="true"></i></a>
													</div>
												<?php endif;?>
                                            </div>
                                        </div>
                                    </div>
                                </div>
								<?php endforeach; ?>
                            </div>
							<?php endif; ?>
							
							<?php 
							foreach($leadershipRoleOrder as $rorder){
								if(isset($leadershipRole[$rorder])&&(count($leadershipRole[$rorder]) >0 && !empty($leadershipRole[$rorder]))){?>		
								<div class="chptr_leadr_card_row">
									<div class="chptr_leadr_heading">
										<p><?php
									if($rorder=="membershipcommittee"):
										echo $this->translator->_('cms.v3.admin.chapterdetails.membershipcommittee'); 
									elseif($rorder=="visitorhost"):
										echo $this->translator->_('cms.v3.admin.chapterdetails.visitorhost'); 	
									elseif($rorder=="support_leaders"):
										echo $this->translator->_('cms.v3.admin.chapterdetails.supportingleaders'); 
									elseif($rorder=="rest_team"):
										echo $this->translator->_('cms.v3.admin.chapterdetails.restoftheteam'); 		
									elseif($rorder=="boardofadvisors"):
										echo $this->translator->_('cms.v3.admin.chapterdetails.iba'); 	
									else:
										echo $rorder;
									endif;
										?></p>
									</div>
									
									<?php
										
									foreach ($leadershipRole[$rorder] as $item) { //print"<pre>";print_r($item);
										$name = $item['firstName'] . ' ' . $item['lastName'];
										if($item['companyName']!=""):
											$companyName=$item['companyName'];
										else:
											$companyName=$item['companyWebsitelink'];
										endif;
										
										if($item['profileImageUrl']!=""):
											$profile_img=$item['profileImageUrl'];
										else:
											$profile_img=$this->config->general->cdn.'/new_template/assets/images/default.svg';
										endif;
										
										$website_link='javascript:;';
										if($item['companyWebsitelink']!=""):
											$website_link=$item['companyWebsitelink'];
											$website_link=parse_url($website_link, PHP_URL_SCHEME)==''?'http://'.$website_link:$website_link;
										endif;
										
									?>
										
										<div class="leaders_card_holder">
											<div class="profile_picture">
												<img src="<?php echo $profile_img;?>" alt="default">
											</div>
											<div class="leadership_card_content_holder">
												<h4 title="<?php echo $name;?>"><?php echo $name; ?></h4>
												<h5 title="<?php echo $item['role'];?>"><?php echo $item['role']; ?></h5>
												<p class="company_name"><a <?php if($website_link!="javascript:;"){?> href="<?php echo $website_link; ?>"  target="_blank" <?php }else{echo 'class="leadership_withoutwebsite"';} ?> title="<?php echo $companyName; ?>"><?php if($companyName!=""): echo $companyName; else: echo '&nbsp;'; endif; ?></a></p>
												<div class="mail_call_profile_viewholder">
													<div class="leftside">
														<?php if(!is_null($item['phone'])&&($item['phone']!="")):?>
														<a href="tel:<?php echo $item['phone']; ?>"><i class="fa fa-phone" aria-hidden="true"></i></a>
														<?php endif;
														if(!is_null($item['email'])&&($item['email']!="")):?>
															<a href="<?php echo 'sendmessage?userId=' . $this->securityUtils->encryptUrlEncoded($item['userId']) . '&userName=' . urlencode($name) ?>"
															   target="_self" class="iconEmail"><i class="fa fa-envelope-o"  data-toggle='tooltip' title='<?php echo $this->translator->_('cms.v3.admin.editpage.sendmessage')?>' aria-hidden="true"></i></a>
														<?php endif; ?>
													</div>
													<?php if(!is_null($item['cmsProfileUrl'])&&($item['cmsProfileUrl']!="N/A")):
															$cmsProfileUrl=$item['cmsProfileUrl'];
															if (strpos($cmsProfileUrl, 'memberdetails') !== false):
																$member_url=explode('memberdetails',$cmsProfileUrl);
																$cmsProfileUrl='memberdetails'.$member_url[1];
															endif;
													?>
														<div class="right_side">
															<a href="<?php echo $cmsProfileUrl;?>"><? echo $this->translator->_('cms.v3.admin.chapterdetails.viewprofile'); ?> <i class="fa fa-angle-right" aria-hidden="true"></i></a>
														</div>
													<?php endif;?>
												</div>
											</div>
										</div>
										
									<?php } ?>
								</div>
								<?php } 
							}
							?>
							<?php 
							
							}?>
							
							
                        </div>

                        

                    </div>
                </div>
            </div>
        </section>
	<?php } ?>
 

