<?= $this->getContent();?>

<div class="row">
        <div class="col-md-12">
            <?php echo $this->tag->linkTo(array('#', '<i class="fa fa-plus fa-lg"></i>', "class" => "newPageModal btn btn-info pull-right", "data-toggle" => "modal", "data-target" => "#newPageModal", "data-href" => $this->url->get('backend/page/add/' . $language->id . '/' . $website->id))); ?>
        </div>
        <hr>
        <br>
    </div>
<?php
if (count($pageContents) > 0) {
    ?>
    <table class='table table-hover table-bordered'>
        <thead>
        <tr>
            <th>Nav Order</th>
            <th>Title</th>
            <th>Last Modified</th>
            <th>Last Published</th>
            <th>Options</th>
        </tr>
        </thead>

        <tbody>
        <?php
        foreach ($pageContents as $pageContent) {
            echo "<tr>";
            echo("<td>" . $pageContent->Page->nav_order . "</td>");
            echo("<td>" . $pageContent->title . "</td>");
            echo("<td>".$pageContent->Page->lastModified."</td>");
            echo("<td>".$pageContent->Page->lastPublished."</td>");
            echo "<td>";
            echo '<div class="btn-group" role="group" aria-label="...">';
            echo $this->tag->linkTo(array('backend/page/view/'.$pageContent->Language->code."/". $pageContent->id, '<i class="fa fa-eye fa-lg"></i>', "class" => "btn btn-primary"));
            echo $this->tag->linkTo(array('#', '<i class="fa fa-wrench fa-lg"></i>', "class" => "editPageModal btn btn-warning","data-toggle" => "modal", "data-target" => "#editPageModal", "id" => "", "data-href" => $this->url->get('backend/page/edit/'. $pageContent->id)));
            echo $this->tag->linkTo(array('backend/page/delete/'.$pageContent->id, '<i class="fa fa-trash-o fa-lg"></i>', "class" => "btn btn-danger"));
            echo "</div>";
            echo "</td>";
            echo "</tr>";
        }
        ?>
        </tbody>
    </table>

    <?php
}else{
    ?>
    <div class="alert alert-warning" role="alert">
        <strong>There are currently no pages for this language</strong>
    </div>
<?php
}
?>

    <div id="newPageModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button title="<?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?>" type="button" class="close" data-dismiss="modal">&times;
                    </button>
                    <h4 class="modal-title">Add a new page</h4>
                </div>
                <div class="modal-body">
                    <iframe src="" style="zoom:0.60" width="100%" height="1200" frameborder="0"></iframe>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        <i class="fa fa-times-circle fa-lg"></i> Close
                    </button>
                </div>
            </div>

        </div>
    </div>

    <div id="editPageModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button title="<?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?>" type="button" class="close" data-dismiss="modal">&times;
                    </button>
                    <h4 class="modal-title">Edit page</h4>
                </div>
                <div class="modal-body">
                    <iframe src="" style="zoom:0.60" width="100%" height="1200" frameborder="0"></iframe>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        <i class="fa fa-times-circle fa-lg"></i> Close
                    </button>
                </div>
            </div>

        </div>
    </div>

    <script>
        $(".newPageModal").on("click", function () {
            var frameSrc = $(this).data("href");
            $('#newPageModal iframe').attr("src", frameSrc);

        });
        $('#newPageModal').on('hidden.bs.modal', function (e) {
            getPages();
        });


        $(".editPageModal").on("click", function () {
            var frameSrc = $(this).data("href");
            $('#editPageModal iframe').attr("src", frameSrc);

        });
        $('#editPageModal').on('hidden.bs.modal', function (e) {
            getPages();
        });
    </script>