<div id="eventDetail">
</div>
<img loading="lazy" id="rssLoaderAjax" style="display: block; margin: 0 auto;"
     src="<?= $this->config->general->cdn; ?>/images/ajax-loader.gif"/>
<script type="text/javascript" data-cookieconsent="ignore">
    //This will make a ajax post request to the event detail controller which return html and we render that in ajax response.
    $(document).ready(function(){
		var basepath=document.location.href;
		$('link[rel="canonical"]').attr('href', basepath);
		$('meta[property="og:url"]').attr('content', basepath);
		$('meta[name="twitter:url"]').attr('content', basepath);
		
        var languages = <?php echo json_encode($languages) ?>;
        var pageMode = <?php echo json_encode($pageMode) ?>;
        var mappedWidgetSettings = '<?php echo json_encode($mappedWidgetSettingsObj) ?>';
        
		$.urlParam = function(name){
			var results = new RegExp('[\?&]' + name + '=([^&#]*)').exec(window.location.href);
			return results[1] || 0;
		}			
		var eventId=decodeURIComponent($.urlParam('eventId'));


        $.ajax({
			type: "POST",
			url: "<?php echo $ajaxUrl; ?>",
			data:{
            mappedWidgetSettings:mappedWidgetSettings,
            pageMode:pageMode,
            languages:languages,
            eventId:eventId},
			success: function(data) {
				$("#rssLoaderAjax").hide();
				$("#eventDetail").html(data);
			}
		});
    });

</script>
