<div id="memberList">
</div>
<img id="rssLoaderAjax" style="display: block; margin: 0 auto;"
     src="<?= $this->config->general->cdn; ?>/images/ajax-loader.gif"/>
<script>
    //This will make a ajax post request to the member list controller which return html and we render that in ajax response.
    $(function () {
        var languages = <?php echo json_encode($languages) ?>;
        var pageMode = <?php echo json_encode($pageMode) ?>;
        var cmsv3 = <?php echo json_encode($cmsv3) ?>;
        var parameters = window.location.href.slice(window.location.href.indexOf('?') + 1);
        var mappedWidgetSettings = '<?php echo json_encode($mappedWidgetSettingsObj) ?>';
		var website_type = $('#website_type').val();
		var website_id = $('#website_id').val();

        <?php
        if($isChapterWebsite) {
        $parameters = "chapterName=" . implode(',', $orgIds) . "&regionIds=" . implode(',', $regionId)."&chapterWebsite=".$isChapterWebsite;
        ?>

        parameters = <?php echo json_encode($parameters) ?>;
        <?php
        }
        ?>

        var url = "<?php echo $ajaxUrl; ?>";
        $.post(url, {
            parameters: parameters,
            languages: languages,
            cmsv3: cmsv3,
			website_type:website_type,
			website_id:website_id,
            mappedWidgetSettings: mappedWidgetSettings,
            pageMode: pageMode
        }, function (data) {
            $("#rssLoaderAjax").hide();
            $("#memberList").html(data);
        });
    });

</script>
