 <div class="col-xs-2 col-sm-3 col-md-12 col-lg-7 colNav hide">
	<ul>
		 <?php
        foreach($navLinks["full"] as $navLink){
            echo "<li class='hidden-xs hidden-sm'>".$navLink."</li>";
        }
        ?>
		
		<li class="hidden-md hidden-lg"><a href="#mobileMenu" class="mobileMenuIcon" data-toggle="mobileMenu" data-target="#mobileMenu"><i class="fa fa-bars"></i></a></li>
	</ul>
</div>



