<?php
if (isset($pageWidget)) {
    ?>
    <div class="box box-default">
        <div class="box-header">
            <div class="box-tools pull-right">
                <?php echo $redirectToUrl; ?>
            </div>
        </div>
        <br>
        <div class="box-body">

            <div class="row">
                <div class="col-md-12">
                    <?= $this->getContent(); ?>
                    <?= $this->flashSession->output(); ?>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <div id="validAlbumName" class="alert alert-danger edit_41"
                         style="display: none"><?php echo $this->translator->_('cms.v3.admin.gallery.albumtitlerequired'); ?></div>
                    <div id="validAlbumDescription" class="alert alert-danger edit_42"
                         style="display: none"><?php echo $this->translator->_('cms.v3.admin.gallery.albumdescrequired'); ?></div>
                    <form id="albumForm" method="post">

                        <?php
                        if (count($mappedWidgetSettings) > 0) {

                            foreach ($mappedWidgetSettings as $mappedWidgetSetting) {
//                                dump($mappedWidgetSetting);

                                if ($mappedWidgetSetting->getFormInputType() == "library") {
                                    $widgetSettingValue = $mappedWidgetSetting->getValue();
                                    if (isset($isError) && $isError == true) {
                                        $widgetSettingValue = $this->request->getPost("edit_" . $mappedWidgetSetting->getId());
                                    }
                                    ?>
                                    <div class="form-group">
                                        <label for="edit_<?= $mappedWidgetSetting->getId() ?>"><?= $mappedWidgetSetting->getTranslateToken() != "" ? $this->translator->_($mappedWidgetSetting->getTranslateToken()) : $mappedWidgetSetting->getName() ?></label>

                                        <div class="input-group">
                                            <input id="edit_<?= $mappedWidgetSetting->getId() ?>"
                                                   name="edit_<?= $mappedWidgetSetting->getId() ?>" type="text"
                                                   value="<?= $widgetSettingValue ?>" class="form-control">
                                            <div class="input-group-btn">
                                                <?php echo $this->tag->linkTo(
                                                    array(
                                                        '#',
                                                        $this->translator->_('cms.v3.admin.slidersettings.browselibrary'),
                                                        "class" => "browseLibraryItemModal btn btn-primary",
                                                        "data-toggle" => "modal",
                                                        "data-target" => "#browseLibraryItemModal",
                                                        "data-input" => "edit_" . $mappedWidgetSetting->getId(),
                                                        "id" => "browser_btn_" . $mappedWidgetSetting->getId(),
                                                        "data-href" => $this->url->get('backend/library/browse/' . $websiteId . "?fileTypeExcluded=pdf"),
                                                        "data-backdrop" => "static", "data-keyboard" => "false"
                                                    )
                                                ); ?>
                                            </div>
                                            <!-- /btn-group -->
                                        </div>
                                    </div>
                                    <?php
                                } else {
                                    $widgetSettingValue = html_entity_decode($mappedWidgetSetting->getValue(),ENT_QUOTES, 'UTF-8');
                                    if (isset($isError) && $isError == true) {
                                        $widgetSettingValue = $this->request->getPost("edit_" . $mappedWidgetSetting->getId());
                                    }

                                    switch ($mappedWidgetSetting->getId()) {

                                        // Testimonial settings
                                        case 19:
                                        case 20:
                                        case 21:
                                        case 22:
                                        case 23:
                                        case 24:
                                            if (!$mappedWidgetSetting->isUsingDefault()) {
                                                ?>
                                                <div class="form-group">
                                                    <label for="edit_<?= $mappedWidgetSetting->getId() ?>"><?= $mappedWidgetSetting->getTranslateToken() != "" ? $this->translator->_($mappedWidgetSetting->getTranslateToken()) : $mappedWidgetSetting->getName() ?></label>
                                                    <input id="edit_<?= $mappedWidgetSetting->getId() ?>"
                                                           name="edit_<?= $mappedWidgetSetting->getId() ?>" type="text"
                                                           value="<?= $widgetSettingValue ?>"
                                                           class="form-control">
                                                </div>
                                                <?php
                                                break;
                                            } else {
                                                ?>
                                                <div class="form-group">
                                                    <label for="edit_<?= $mappedWidgetSetting->getId() ?>"><?= $mappedWidgetSetting->getTranslateToken() != "" ? $this->translator->_($mappedWidgetSetting->getTranslateToken()) : $mappedWidgetSetting->getName() ?></label>
                                                    <input id="edit_<?= $mappedWidgetSetting->getId() ?>"
                                                           name="edit_<?= $mappedWidgetSetting->getId() ?>" type="text"
                                                           value=""
                                                           class="form-control">
                                                </div>
                                                <?php
                                                break;
                                            }

                                        // Slider transition setting
                                        case 40:
                                            ?>
                                            <div class="form-group">
                                                <label for="edit_<?= $mappedWidgetSetting->getId() ?>"><?= $mappedWidgetSetting->getTranslateToken() != "" ? $this->translator->_($mappedWidgetSetting->getTranslateToken()) : $mappedWidgetSetting->getName() ?></label>
                                                <input id="edit_<?= $mappedWidgetSetting->getId() ?>"
                                                       name="edit_<?= $mappedWidgetSetting->getId() ?>" type="text"
                                                       value="<?= $widgetSettingValue != "" ? $widgetSettingValue : 9 ?>"
                                                       class="form-control">
                                            </div>
                                            <?php
                                            break;

                                        default:
                                            ?>
                                            <div class="form-group">
                                                <label for="edit_<?= $mappedWidgetSetting->getId() ?>"><?= $mappedWidgetSetting->getTranslateToken() != "" ? $this->translator->_($mappedWidgetSetting->getTranslateToken()) : $mappedWidgetSetting->getName() ?></label>
                                                <input id="edit_<?= $mappedWidgetSetting->getId() ?>"
                                                       name="edit_<?= $mappedWidgetSetting->getId() ?>" type="text"
                                                       value="<?=  html_entity_decode($widgetSettingValue) ?>"
                                                       class="form-control">
                                            </div>
                                            <?php
                                            break;
                                    }
                                }
                            }

                        }
                        ?>

                        <button type="submit"
                                class="btn btn-primary <?php echo $buttonPullDirection; ?>"><?= $this->translator->_('cms.v3.admin.editpage.savebtn'); ?></button>
                    </form>
                </div>
            </div>

        </div>
        <!-- /.box-body -->
    </div>

    <div id="browseLibraryItemModal" class="modal fade" role="dialog">
        <div class="modal-dialog modal-lg">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button title="<?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?>" type="button"
                            class="close" data-dismiss="modal">&times;
                    </button>
                    <h4 class="modal-title"><?php echo $this->translator->_('cms.v3.admin.editpage.selectanimagefromlibrary'); ?></h4>
                </div>
                <div class="modal-body">
                    <iframe id='FileFrame' src="" style="zoom:0.60" width="100%" height="1200"
                            frameborder="0"></iframe>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">
                        <i class="fa fa-times-circle fa-lg"></i> <?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?>
                    </button>
                </div>
            </div>

        </div>
    </div>

    <script>
        $(".browseLibraryItemModal").on("click", function () {
            window.localStorage.setItem('browseLibraryButtonId', $(this).attr("id"));

            $('#browseLibraryItemModal iframe').attr("src", $(this).data("href"));
        });

        $("#browseLibraryItemModal").on('hide.bs.modal', function () {
            $("#FileFrame")[0].contentWindow.removeImages();
        });

        $("#browseLibraryItemModal").on('shown.bs.modal', function () {
            var lastFileCount = 0;
            var timingInterval = setInterval(function () {
                // To prevent a timing issue with the rendering of the DOM and images, keep trying to add the click handler whilst we don't have any images
                if (lastFileCount > 0 && lastFileCount == $("#FileFrame").contents().find(".img-thumb").length) {
                    clearInterval(timingInterval);

                    var timingInterval2 = setInterval(function () {
                        clearInterval(timingInterval2);
                        $("#FileFrame").contents().find(".img-thumb").on("click", function () {

                            $("#FileFrame").contents().find(".img-thumb").removeClass('selected'); // removes the previous selected class
                            $(this).addClass('selected'); // adds the class to the clicked image

                            var selectedimage = $(this).data("imgp");
                            $("#browseLibraryItemModal").modal("hide");

                            var buttonId = window.localStorage.getItem("browseLibraryButtonId");
                            if (buttonId) {
                                $("#" + buttonId).parent().parent().find("input").val(selectedimage);
                            } else {
                                console.error("Could not extract clicked button ID, this should never happen?!");
                            }
                        });
                    }, 150);
                }
                lastFileCount = $("#FileFrame").contents().find(".img-thumb").length;
            }, 150);
        });

        function isTextValid(id) {
            if (!$("#" + id).val().trim()) {
                $("." + id).show();
                return false;
            }
            $("." + id).hide();
            return true;
        }

        $("#albumForm").on('submit', function (e) {
            var name = isTextValid("edit_41");
            var description = isTextValid("edit_42");

            // Prevent the album being saved if there are errors in any of the fields
            if (!(name && description)) {
                e.preventDefault();
            }
        });

    </script>

    <?php
} else {
    ?>
    <div class="alert alert-warning" role="alert">
        <strong>All supported widgets have been added</strong>
    </div>
<?php } ?>
