<?php
$this->partial('partials/v3/page/page-header');

$widgetProperties = array();
$widgetProperties["languages"] = $languages;
$widgetProperties["orgIds"] = $orgIds;
$widgetProperties["page"] = $page;
$widgetProperties["domainName"] = $domainName;

if (isset($renderStaticContent)) {
    $widgetProperties['renderStaticContent'] = $renderStaticContent;
}

$this->widgetRenderService->renderWidgets($pageWidgets, $widgetProperties);

$this->partial('partials/v3/footer/footer');
?>