<?php
$this->partial('partials/v3/page/page-header');
$widgetProperties = array();
$widgetProperties["languages"] = $languages;
$widgetProperties["pageMode"] = $pageMode;
$widgetProperties["domainName"] = $domainName;
$widgetProperties["renderStaticContent"] = $renderStaticContent;

$this->widgetRenderService->renderWidgets($pageWidgets,$widgetProperties);

$this->partial('partials/v3/footer/footer');

?>
