<?php
$this->partial('partials/v3/page/page-header');
$widgetProperties = array();
$widgetProperties["languages"] = $languages;
$widgetProperties["orgIds"] = $orgIds;
$widgetProperties["domainName"] = $domainName;
if(isset($renderStaticContent)){
    $widgetProperties['renderStaticContent'] = $renderStaticContent;
}

// this region is hard coded at the moment in order to be able to test it using the default region website
$this->widgetRenderService->renderWidgets($pageWidgets, $widgetProperties);

$this->partial('partials/v3/footer/footer');