<section class="widgetPageHeader" style="background: url('<?php echo $this->config->general->cdn; ?>/new_template/assets/images/innerpage_banners.jpg') no-repeat center center; background-size: cover;">
    <div class="holder">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <h1><?php echo isset($contentSettings["pagecontent_lead_heading"]) ?  $contentSettings["pagecontent_lead_heading"] : "pagecontent_lead_heading" ?></h1>
        </div>
    </div>
</section>

<?php
$widgetProperties = array();
$widgetProperties["languages"] = $languages;
$widgetProperties["orgIds"] = $orgIds;
$widgetProperties["page"] = $page;
$widgetProperties['renderStaticContent'] = $renderStaticContent;
$widgetProperties["domainName"] = $domainName;

$this->widgetRenderService->renderWidgets($pageWidgets,$widgetProperties);
?>

<?php $this->partial('partials/v3/footer/footer'); ?>
