<?php $this->partial('partials/v3/page/page-header'); ?>

<?php
$widgetProperties = array();
$widgetProperties["languages"] = $languages;
$widgetProperties["orgIds"] = $orgIds;
$widgetProperties["pageMode"] = $pageMode;
$widgetProperties["domainName"] = $domainName;

if(isset($renderStaticContent)){
    $widgetProperties['renderStaticContent'] = $renderStaticContent;
}

if (isset($regionId)) {
    $widgetProperties["regionId"] = $regionId;
}

$this->widgetRenderService->renderWidgets($pageWidgets,$widgetProperties);

$this->partial('partials/v3/footer/footer');
?>