<?php $this->partial('partials/v3/page/page-header'); ?>

<section class="widgetDataTable">

    <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper form-inline dt-bootstrap no-footer">
        <div class="row">
            <div class="col-sm-6"></div>
            <div class="col-sm-6">
                <div id="DataTables_Table_0_filter" class="dataTables_filter"><label><i class="fa fa-filter"
                                                                                        data-toggle='tooltip' title='<?php echo $this->translator->_('cms.v3.admin.editpage.search')?>'  aria-hidden="true"></i><input
                                type="search" class="form-control input-sm" placeholder=""
                                aria-controls="DataTables_Table_0"></label></div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <table class="table table-hover listtables dataTable no-footer dtr-inline" width="100%"
                       id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info"
                       style="width: 100%;">
                    <thead>
                    <tr role="row">
                        <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                            style="width: 266px;" aria-label="Member Names: activate to sort column ascending">Member
                            Names
                        </th>
                        <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                            style="width: 185px;" aria-label="Chapter - Region: activate to sort column ascending">
                            Chapter - Region
                        </th>
                        <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                            style="width: 69px;" aria-label="City: activate to sort column ascending">City
                        </th>
                        <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                            style="width: 69px;" aria-label="Area: activate to sort column ascending">Area
                        </th>
                        <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                            style="width: 131px;" aria-label="Profession/Specialty: activate to sort column ascending">
                            Profession/Specialty
                        </th>
                        <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1"
                            style="width: 108px;" aria-label="Company: activate to sort column ascending">Company
                        </th>
                    </tr>
                    </thead>
                    <tbody>

                    <tr>
                        <td colspan="6" class="group groupexact"><span class="2999">Exact Matches</span></td>
                    </tr>
                    <tr role="row" class="odd">
                        <td tabindex="0"><a
                                    href="memberdetails.php?memberId=1694&amp;t=38d372524ccf2ab1e6e62c2f9253f4d7ec428cfcd5735c2bb35434c6104b543e&amp;name=Chennai+Invoice+9a+1"
                                    class="linkone">Chennai Invoice 9a 1</a></td>
                        <td>CHN Super Kings - Chennai CBD (A)</td>
                        <td>City, State</td>
                        <td></td>
                        <td>Accounting &gt; Accounting Services</td>
                        <td>Testing Services Ltd</td>
                    </tr>
                    <tr role="row" class="even">
                        <td tabindex="0"><a
                                    href="memberdetails.php?memberId=1462&amp;t=061bf6f7b4a76d55ed9b5ca480b4fa712a6ed684434c327a011678ee702116cf&amp;name=Kav+Test"
                                    class="linkone">Kav Test</a></td>
                        <td>CHN Super Kings - Chennai CBD (A)</td>
                        <td>Chennai, TN</td>
                        <td></td>
                        <td>Advertising &gt; Advertising Agency</td>
                        <td></td>
                    </tr>
                    <tr role="row" class="odd">
                        <td tabindex="0"><a
                                    href="memberdetails.php?memberId=1465&amp;t=72fc752857d5fed54131ff54282f6fc9754c49a44e1bec709dd635e953bb4367&amp;name=Shan+test+b589"
                                    class="linkone">Shan test b589</a></td>
                        <td>CHN Super Kings - Chennai CBD (A)</td>
                        <td></td>
                        <td></td>
                        <td>Appliances &gt; Appliance Sales</td>
                        <td></td>
                    </tr>
                    <tr role="row" class="even">
                        <td tabindex="0"><a
                                    href="memberdetails.php?memberId=1697&amp;t=37206d6070c6150c84f1d9aa8a7b69a112f084f6bd9642aa9e891290035ce433&amp;name=Shrinidhi+bhat"
                                    class="linkone">Shrinidhi bhat</a></td>
                        <td>Test1 - Chennai CBD (A)</td>
                        <td></td>
                        <td></td>
                        <td>Accounting &gt; Accounting Services</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td colspan="6" class="group"><span class="6000">Best Matches</span></td>
                    </tr>
                    <tr>
                        <td colspan="6" class="notfound">Your search criteria produced no best matches</td>
                    </tr>
                    </tbody>
                </table>
                <div id="DataTables_Table_0_processing" class="dataTables_processing panel panel-default"
                     style="display: none;">Processing...
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="dataTables_info" id="DataTables_Table_0_info" role="status" aria-live="polite">Showing 1 to
                    4 of 4 entries
                </div>
            </div>
            <div class="col-sm-7">
                <div class="dataTables_paginate paging_full_numbers" id="DataTables_Table_0_paginate">
                    <ul class="pagination">
                        <li class="paginate_button first disabled" id="DataTables_Table_0_first"><a href="#"
                                                                                                    aria-controls="DataTables_Table_0"
                                                                                                    data-dt-idx="0"
                                                                                                    tabindex="0"><i
                                        class="fa fa-step-backward" aria-hidden="true"></i></a></li>
                        <li class="paginate_button previous disabled" id="DataTables_Table_0_previous"><a href="#"
                                                                                                          aria-controls="DataTables_Table_0"
                                                                                                          data-dt-idx="1"
                                                                                                          tabindex="0"><i
                                        class="fa fa-chevron-left" aria-hidden="true"></i></a></li>
                        <li class="paginate_button active"><a href="#" aria-controls="DataTables_Table_0"
                                                              data-dt-idx="2" tabindex="0">1</a></li>
                        <li class="paginate_button next disabled" id="DataTables_Table_0_next"><a href="#"
                                                                                                  aria-controls="DataTables_Table_0"
                                                                                                  data-dt-idx="3"
                                                                                                  tabindex="0"><i
                                        class="fa fa-chevron-right" aria-hidden="true"></i></a></li>
                        <li class="paginate_button last disabled" id="DataTables_Table_0_last"><a href="#"
                                                                                                  aria-controls="DataTables_Table_0"
                                                                                                  data-dt-idx="4"
                                                                                                  tabindex="0"><i
                                        class="fa fa-step-forward" aria-hidden="true"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        var oTable;
        var oDefault;
        var oSettings;
        var clearHeaders;
        var storedGroups;
        var storedGroupString1;
        var storedGroupString2;
        var iColspan;
        $(function () {

            $.fn.dataTableExt.oSort["string-asc"] = function (x, y) {
                return x.toString().localeCompare(y.toString());
            };

            $.fn.dataTableExt.oSort["string-desc"] = function (x, y) {
                return y.toString().localeCompare(x.toString());
            };

            $.fn.dataTableExt.oSort["time-sort-asc"] = function (x, y) {
                var d1 = new Date();
                var time = x.match(/(\d+)(?::(\d\d))?\s*(p?)/i);
                var time1 = x.match(/(\d+)(?::(\d\d))?\s*(a?)/i);
                d1.setHours(parseInt(time[1]) + ((time[1] != "12") ? (time[3] ? 12 : 0) : (time[3] ? 0 : time1[3] ? -12 : 0)));
                d1.setMinutes(parseInt(time[2]) || 0);

                var d2 = new Date();
                time = y.match(/(\d+)(?::(\d\d))?\s*(p?)/i);
                time1 = y.match(/(\d+)(?::(\d\d))?\s*(a?)/i);
                d2.setHours(parseInt(time[1]) + ((time[1] != "12") ? (time[3] ? 12 : 0) : (time[3] ? 0 : time1[3] ? -12 : 0)));
                d2.setMinutes(parseInt(time[2]) || 0);

                x = d1.getTime();
                y = d2.getTime();

                return ((x < y) ? -1 : ((x > y) ? 1 : 0));
            };

            $.fn.dataTableExt.oSort["time-sort-desc"] = function (x, y) {
                var d1 = new Date();
                var time = x.match(/(\d+)(?::(\d\d))?\s*(p?)/i);
                var time1 = x.match(/(\d+)(?::(\d\d))?\s*(a?)/i);
                d1.setHours(parseInt(time[1]) + ((time[1] != "12") ? (time[3] ? 12 : 0) : (time[3] ? 0 : time1[3] ? -12 : 0)));
                d1.setMinutes(parseInt(time[2]) || 0);

                var d2 = new Date();
                time = y.match(/(\d+)(?::(\d\d))?\s*(p?)/i);
                time1 = y.match(/(\d+)(?::(\d\d))?\s*(a?)/i);
                d2.setHours(parseInt(time[1]) + ((time[1] != "12") ? (time[3] ? 12 : 0) : (time[3] ? 0 : time1[3] ? -12 : 0)));
                d2.setMinutes(parseInt(time[2]) || 0);

                x = d1.getTime();
                y = d2.getTime();

                return ((x < y) ? 1 : ((x > y) ? -1 : 0));
            };

            storedGroups = new Array();
            storedGroupString1 = new Array();
            storedGroupString2 = new Array();

            var storedHeaderIndex = 0;
            var nOrigTrs = $(".listtables tbody tr");
            for (var i = 0; i < nOrigTrs.length; i++) {
                if ($("td:eq(2)", nOrigTrs[i]).html() == "false") {
                    storedGroups[storedHeaderIndex] = i;
                    storedGroupString1[storedHeaderIndex] = $("td:eq(0)", nOrigTrs[i]).html();
                    storedGroupString2[storedHeaderIndex] = $("td:eq(1)", nOrigTrs[i]).html();
                    nOrigTrs[i].parentNode.removeChild(nOrigTrs[i]);
                    storedHeaderIndex++;
                }
            }

            oDefault = {
                "bProcessing": true,
                "responsive": true,
                "bServerSide": false,
                "bLengthChange": false,
                "iDisplayLength": 1000,
                "bSort": true,
                "bInfo": true,
                "bPaginate": true,
                "sPaginationType": "full_numbers",
                "aaSortingFixed": [[0, 'asc']],
                "aaSorting": [],
                "fnDrawCallback": function (oSettings) {
                    if (oSettings.aiDisplay.length == 0) {
                        $('.dataTables_empty').text(storedGroupString2[0]);
                        var nTrs = $('.dataTables_empty').parent();
                        var nGroup = document.createElement('tr');
                        var nCell = document.createElement('td');
                        iColspan = 6;
                        nCell.colSpan = iColspan;
                        nCell.className = "group groupexact";
                        nCell.innerHTML = storedGroupString1[0];
                        nGroup.appendChild(nCell);
                        nTrs[0].parentNode.insertBefore(nGroup, nTrs[0]);
                        return;
                    }

                    var nTrs = $('.listtables tbody tr');

                    var nextHeaderIndex = 0;
                    var startLength = nTrs.length - 1;

                    var iColspan = nTrs[0].getElementsByTagName('td').length;
                    var sLastGroup = "";

                    for (var i = 0; i < nTrs.length; i++) {
                        var iDisplayIndex = oSettings._iDisplayStart + i;

                        if (nextHeaderIndex < storedGroups.length && (iDisplayIndex == storedGroups[nextHeaderIndex] || (i == startLength && storedGroups[nextHeaderIndex] > i))) {
                            var nGroup = document.createElement("tr");
                            var nCell = document.createElement("td");
                            iColspan = 6;
                            nCell.colSpan = iColspan;
                            nCell.className = "group";
                            nCell.innerHTML = storedGroupString1[nextHeaderIndex];
                            nGroup.appendChild(nCell);
                            if (i == startLength) {
                                nTrs[i].parentNode.insertBefore(nGroup, nTrs[i].nextSibling);
                            } else {
                                nTrs[i].parentNode.insertBefore(nGroup, nTrs[i]);
                            }

                            var nfGroup = document.createElement("tr");
                            var nfCell = document.createElement("td");
                            nfCell.colSpan = iColspan;
                            nfCell.className = "notfound";
                            nfCell.innerHTML = storedGroupString2[nextHeaderIndex];
                            nfGroup.appendChild(nfCell);
                            if (i == startLength) {
                                nTrs[i].parentNode.insertBefore(nfGroup, nTrs[i].nextSibling.nextSibling);
                            } else {
                                nTrs[i].parentNode.insertBefore(nfGroup, nTrs[i]);
                            }

                            nextHeaderIndex++;
                        }


                        var sGroup = oSettings.aoData[oSettings.aiDisplay[iDisplayIndex]]._aData[0];
                        if (sGroup != sLastGroup) {
                            var nGroup = document.createElement('tr');
                            var nCell = document.createElement('td');
                            nCell.colSpan = iColspan;
                            nCell.className = "group";
                            nCell.innerHTML = sGroup;
                            nGroup.appendChild(nCell);
                            nTrs[i].parentNode.insertBefore(nGroup, nTrs[i]);
                            sLastGroup = sGroup;
                        }
                    }
                    $(".listtables td.group:eq(0)").addClass("groupexact");
                }
            };

            oSettings = $.extend(true, {}, oDefault);

            oSettings.oLanguage = {
                sLengthMenu: "Show _MENU_ entries",
                sSearch: "<i class='fa fa-filter' aria-hidden='true'></i>",
                sZeroRecords: "...",
                sEmptyTable: "...",
                sInfo: "Showing _START_ to _END_ of _TOTAL_ entries",
                sInfoEmpty: "Showing 0 to 0 of 0 entries",
                sInfoFiltered: "",
                oPaginate: {
                    sFirst: "<i class='fa fa-step-backward' aria-hidden='true'></i>",
                    sPrevious: "<i class='fa fa-chevron-left' aria-hidden='true'></i>",
                    sNext: "<i class='fa fa-chevron-right' aria-hidden='true'></i>",
                    sLast: "<i class='fa fa-step-forward' aria-hidden='true'></i>"
                }
            };

            oSettings.aoColumns = [
                {bVisible: false, sType: "string"},
                {sWidth: "30%", sTitle: "Member Names"},
                {sWidth: "20%", sTitle: "Chapter - Region"},
                {sWidth: "10%", sTitle: "City"},
                {sWidth: "10%", sTitle: "Area"},
                {sWidth: "15%", sTitle: "Profession/Specialty"},
                {sWidth: "15%", sTitle: "Company"}
            ];

            oTable = $('.listtables').dataTable(oSettings);
        });
    </script>
</section>

<?php
$widgetProperties = array();

$this->widgetRenderService->renderWidgets($pageWidgets,$widgetProperties);
?>


<!-- FOOTER WIDGET -->
<?php $this->partial('partials/v3/footer/footer-widgets'); ?>
<?php $this->partial('partials/v3/footer/footer-newsletter'); ?>

<footer>
    <?php $this->partial('partials/v3/footer/footer-links'); ?>
    <?php $this->partial('partials/v3/footer/copyright-bar'); ?>
</footer>

<?php $this->partial('partials/v3/footer/mobile-navbar'); ?>

</body>
</html>

