<div class="box box-default">
    <div class="box-header">
        <div class="box-tools pull-right">
            <?php echo isset($redirectToUrl) ?  $redirectToUrl : ""; ?>
        </div>
    </div>
    <br>
    <div class="box-body">

        <div class="row">
            <div class="col-md-12">
                <?= $this->getContent(); ?>
                <?= $this->flashSession->output(); ?>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <form method="post">
					<div class="form-group">
                        <label for="contentTitle"><?php echo $this->translator->_('cms.v3.admin.editpage.pagecustomtitle'); ?></label>
                        <input type="text" class="form-control" name="contentTitle" id="contentTitle"
                               value="<?php if (isset($customTitle)) {
                                   echo $customTitle;
                               } ?>">
                    </div>
					
					<div class="form-group">
                        <label for="contentAlt"><?php echo $this->translator->_('cms.v3.admin.editpage.pagecustomalt'); ?></label>
                        <input type="text" class="form-control" name="contentAlt" id="contentAlt"
                               value="<?php if (isset($customAlt)) {
                                   echo $customAlt;
                               } ?>">
                    </div>
				
                    <div class="form-group">
                        <label for="contentUrl"><?= $this->translator->_('cms.v3.admin.editpage.podcastcontenturl'); ?></label>
                        <input type="text" class="form-control" name="contentUrl" id="contentUrl"
                               value="<?php if (isset($contentUrl)) {
                                   echo $contentUrl;
                               } ?>">
                    </div>
                    <div class="form-group">
                        <label for="customimgpath"><?= $this->translator->_('cms.v3.admin.editpage.podcastcustomimgpath'); ?></label>

                        <div class="input-group">
                            <input type="text" class="form-control" name="customimgpath" id="customimgpath"
                                   value="<?php if (isset($customimgpath)) {
                                       echo $customimgpath;
                                   } ?>">
                            <div class="input-group-btn">
                                <?php echo $this->tag->linkTo(
                                    array(
                                        '#',
                                        $this->translator->_('cms.v3.admin.slidersettings.browselibrary'),
                                        "class" => "browseLibraryItemModal btn btn-primary",
                                        "data-toggle" => "modal",
                                        "data-target" => "#browseLibraryItemModal",
                                        "data-input" => "customimgpath",
                                        "id" => "customimgpath",
                                        "data-href" => $this->url->get('backend/library/browse/' . $websiteId . "?fileTypeExcluded=pdf"),
                                        "data-backdrop" => "static", "data-keyboard" => "false"
                                    )
                                ); ?>
                            </div>
                            <!-- /btn-group -->
                        </div>

                    </div>
                    <button type="submit"
                            class="btn btn-primary <?php echo $buttonPullDirection; ?>"><?= $this->translator->_('cms.v3.admin.editpage.savebtn'); ?></button>


                </form>
            </div>
            <div id="browseLibraryItemModal" class="modal fade" role="dialog">
                <div class="modal-dialog modal-lg">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button title="<?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?>"
                                    type="button"
                                    class="close" data-dismiss="modal">&times;
                            </button>
                            <h4 class="modal-title"><?php echo $this->translator->_('cms.v3.admin.editpage.selectanimagefromlibrary'); ?></h4>
                        </div>
                        <div class="modal-body">
                            <iframe id='FileFrame' src="" style="zoom:0.60" width="100%" height="1200"
                                    frameborder="0"></iframe>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-danger" data-dismiss="modal">
                                <i class="fa fa-times-circle fa-lg"></i> <?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?>
                            </button>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(".browseLibraryItemModal").on("click", function () {
        window.localStorage.setItem('browseLibraryButtonId', $(this).attr("id"));

        $('#browseLibraryItemModal iframe').attr("src", $(this).data("href"));
    });

    $("#browseLibraryItemModal").on('hide.bs.modal', function () {
        $("#FileFrame")[0].contentWindow.removeImages();
    });

    $("#browseLibraryItemModal").on('shown.bs.modal', function () {
        var timingInterval = setInterval(function () {
            // To prevent a timing issue with the rendering of the DOM and images, keep trying to add the click handler whilst we don't have any images
            if ($("#FileFrame").contents().find(".img-thumb").length) {
                clearInterval(timingInterval);
            }

            $("#FileFrame").contents().find(".img-thumb").on("click", function () {

                $("#FileFrame").contents().find(".img-thumb").removeClass('selected'); // removes the previous selected class
                $(this).addClass('selected'); // adds the class to the clicked image

                var selectedimage = $(this).data("imgp");
                $("#browseLibraryItemModal").modal("hide");

                var buttonId = window.localStorage.getItem("browseLibraryButtonId");
                if (buttonId) {
                    $("#" + buttonId).parent().parent().find("input[name=customimgpath]").val(selectedimage);
                } else {
                    console.error("Could not extract clicked button ID, this should never happen?!");
                }
            });
        }, 50);
    });
</script>