<script src="/bnicms/v3/js/modalClose/closeModal.js"></script>
<?= $this->getContent();?>
<div class="row modal-row">
      <div class="col-md-12">
            <form method="post">
                <div class="form-group">
                    <label for="headingText"><?= $this->translator->_('cms.v3.admin.editpage.headingtext'); ?></label>
                    <input type="text" class="form-control" name="headingText" id="headingText" value="<?php if(isset($headingText)){ echo $headingText;}?>">
                </div>
            </form>
        </div>
    </div>


<script>
    // When the document is ready, check on intervals if the success alert is on display.
    // If the success alert is on display then this means we've successfully completed our action and we can close the form
    // Close modal function is highly specific to the bootstrap modal and expects some sort of successful alert in this file to process
    $(document).ready(function(){
        closeModal('#pageContentSettingsModal');
    });
</script>