<div id="album-ui-sortable-handle-cloneable">
    <div class="item ui-sortable-handle" id="_PAGE_CONTENT_WIDGET_ID_">
        <div class="cols">
            <h3><?php echo $this->translator->_('cms.v3.admin.widget.albumwidget'); ?></h3>
        </div>
        <div class="cols colSmall">
            <a href="<?php echo $this->config->general->baseUri; ?>backend/album/manage/_PAGE_CONTENT_WIDGET_ID_" class="iconLink" title="<?php echo $this->translator->_('cms.v3.admin.editpage.configurealbum'); ?>"><i class="fa fa-cogs" aria-hidden="true"></i></a>
        </div>
        <div class="cols colSmall">
            <a href="<?php echo $this->config->general->baseUri; ?>backend/pagecontentwidget/edit/_PAGE_CONTENT_WIDGET_ID_" class="iconLink" title="<?php echo $this->translator->_('cms.v3.admin.editpage.editalbum'); ?>">
                <i class="fa fa-pencil" aria-hidden="true"></i>
            </a>
        </div>

        <div class="cols colSmall">
            <a href="#" class="iconLink deleteWidget" data-wid="_PAGE_CONTENT_WIDGET_ID_" title="<?php echo $this->translator->_('cms.v3.admin.editpage.deletealbum'); ?>"><i class="fa fa-trash-o" aria-hidden="true"></i></a>
        </div>
    </div>
</div>