<div class="files" id="holder">
    <form method="post">
        <div class="images">
            <?php
            foreach ($images as $image) {
                ?>
                <a class="thumb">
                    <img id="<?= $image->filename ?>"
                         src="<?= $this->url->get('backend/render/renderImage/' . $image->thumbnail_id) ?>"
                         data-src="<?= $this->url->get('backend/render/renderImage/' . $image->_id) ?>"
                         class="img-thumb"
                         width="304" height="236"/>
                    <span class="filename">
                        <label>
                            <input id="selectedImages[]" name="selectedImages[]" data-id="<?= $image->_id ?>"
                                   data-file-name="<?= $image->filename ?>" type="checkbox"
                                   class="image"><?php echo $image->filename; ?>
                        </label>
                        <br>
                        <?= $this->translationUtils->formatDate($image->uploadDate->toDateTime()->format('Y-m-d H:i:s'), $userTimezone); ?>
                        <br>
                        <?= $this->viewHelper->formatBytes((double)$image->length); ?>
                        <br>
                    </span>
                </a>
                <?php
            }
            ?></div>
        <div class="documents" style="display: none">
            <?php
            foreach ($documents as $document) {
                ?>
                <a class="thumb">
                    <i class="fa fa-file-pdf-o" aria-hidden="true" style="font-size: 5em"></i>
                    <span class="filename" data-file-name="<?= $document->filename ?>"
                          data-file-src="<?= $this->url->get('backend/render/renderDocument/' . $document->_id) ?>">
                        <label>
                            <input id="selectedImages[]" name="selectedImages[]" data-id="<?= $document->_id ?>"
                                   data-file-name="<?= $document->filename ?>" type="checkbox"
                                   class="document"><?php echo $document->filename; ?>
                        </label>
                        <br>
                        <?= $this->translationUtils->formatDate($document->uploadDate->toDateTime()->format('Y-m-d H:i:s'), $userTimezone); ?>
                        <br>
                        <?= $this->viewHelper->formatBytes((double)$document->length); ?>
                    </span>
                </a>

                <?php
            }
            ?></div>
    </form>


    <!-- Modal -->
    <div class="modal fade" id="filePreview" tabindex="-1" role="dialog" aria-labelledby="filePreviewLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button title=<?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?> type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="filePreviewLabel" style="overflow: hidden">Preview</h4>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <a href="#" id="filePreviewDownload" type="button" class="btn btn-default" download="#"><i
                                class="fa fa-download" aria-hidden="true"></i> <?php echo $this->translator->_('cms.v3.admin.modal.download'); ?></a>
                    <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?></button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>

    $(".images .thumb").dblclick(function () {
        // Get the url of the image
        var imgSrc = $(this).children('img').attr("data-src");
        var imgName = $(this).children('img').attr("id");
        var previewing = '<?php echo addslashes(html_entity_decode($this->translator->_('cms.v3.admin.modal.previewing'),ENT_QUOTES, 'UTF-8')); ?>';
        $('#filePreview #filePreviewLabel').html(previewing+' '+ imgName);

        // Display the full image in the modal
        $('#filePreview .modal-body').html('<img class="img-responsive" src="' + imgSrc + '" />');

        $('#filePreview #filePreviewDownload').attr("href", imgSrc);
        $('#filePreview #filePreviewDownload').attr("download", imgName);

        $('#filePreview').modal('show');
    });


    $(".documents .thumb").dblclick(function () {

        var documentSrc = $(this).children('.filename').data("file-src");
        var documentName = $(this).children('.filename').data("file-name");
        var previewing = '<?php echo addslashes(html_entity_decode($this->translator->_('cms.v3.admin.modal.previewing'),ENT_QUOTES, 'UTF-8')); ?>';
        $('#filePreview #filePreviewLabel').html(previewing+' '+ documentName);

        $('#filePreview .modal-body').html('<div class="embed-responsive embed-responsive-16by9"> <object  data="' + documentSrc + '"height="100%" width="100%" type="application/pdf"/> </div>');

        $('#filePreview #filePreviewDownload').attr("href", documentSrc);
        $('#filePreview #filePreviewDownload').attr("download", documentName);

        $('#filePreview').modal('show');
    });
</script>