
<?php
$heightStyle = "";
if (isset($modalBodyHeight)) {
    $heightStyle = "style=\"height:{$modalBodyHeight}\"";
}
?>

<div id="<?php echo $wrapperId ?>" class="modal fade" role="dialog" style="z-index:10000">
    <div class="modal-dialog modal-lg">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button title="<?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?>" type="button" class="close" data-dismiss="modal">&times;
                </button>
                <h4 class="modal-title"><?php echo $title; ?></h4>
            </div>
            <div class="modal-body" <?php echo $heightStyle ?>>
                <div id="modalLoadingBackground"></div>
                <div id="modalLoadingSpinner">
                    <img id="modal-spinner" src="<?= $this->config->general->cdn;?>/images/published-action-loader.gif" />
                </div>
                <iframe id="<?php echo $iframeId; ?>" src="" class="iframe-modal" width="100%" height="100%" frameborder="0"></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal"><?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?></button>
                <button type="button" class="btn btn-success" id="<?php echo $successButtonId ?>"><?= $this->translator->_('cms.v3.admin.modal.savebtn'); ?></button>
                <div style="clear:both"></div>
            </div>
        </div>

    </div>
</div>