<div class="container">
    <?= $this->getContent(); ?>
    <div class="row">
        <div class="col-md-12">


            <h1>Hello, world!</h1>


            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                Launch demo modal
            </button>

            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button title="<?php echo $this->translator->_('cms.v3.admin.modal.closebtn'); ?>" type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                        </div>
                        <div class="modal-body">
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button id="clart" name="clart" type="button" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </div>


    </div>
</div>



        <script>
            $(document).ready(function () {



                $("#myModal").on("show.bs.modal", function (e) {

                    $.ajax({
                        type: 'get',
                        url: 'https://www.mseymourbniscale/bnicms/v3/backend/page/edit/6744/10301',
                        dataType: 'html',
                        success: function (data) {
                            console.log(data);
                            $(".modal-body").html(data);

                            // ADD THIS
                            // $('#editPageEditor).ckeditor();
                        }
                    });

//            $.get('/index/display/', function (data) {
//                $(".modal-body").html(data);
//            });
                });

                $("#myModal").on("hidden.bs.modal", function (e) {
                    $(".modal-body").html("");
                });

                $("#clart").on("click", function (e) {
                    $.ajax({
                        type: 'post',
                        url: '/index/process/',
                        data: $('form').serialize(),
                        dataType: 'json',
                        success: function (data) {
                            if (data['success']) {
                                $("#clart").hide();
                                $("#success").show();
                            }
                        }
                    });
                });
            });
        </script>


