<div id="success" class="alert alert-success" style="display:none">
    success
</div>
<div id="clart">
    <h2>
        Sign up using this form
    </h2>
    <?php echo $this->tag->form("index/display"); ?>

    <p>
        <label for="name">
            Name
        </label>

        <?php echo $this->tag->textField("name"); ?>
    </p>

    <p>
        <label for="email">
            E-Mail
        </label>

        <?php echo $this->tag->textField("email"); ?>
    </p>


    </form>
</div>
