<div class="container">
    <?= $this->getContent();?>
    <div class="row">
        <div class="col-md-12">
            <form method="post">
                <div class="form-group">
                    <label for="navItemName">Name</label>
                    <input type="text" class="form-control" name="navItemName" id="navItemName" placeholder="Name">
                </div>
                <div class="form-group">
                    <label for="navItemDescription">Description</label>
                    <input type="text" class="form-control" name="navItemDescription" id="navItemDescription" placeholder="Description">
                </div>
                <div class="form-group">
                    <label for="navItemPages">Page</label>
                    <select name="navItemPages" id="navItemPages" class="form-control">
                        <?php
                        foreach ($pages as $page) {
                            echo "<option value='" . $page->id . "'>" . $page->title . "</option>";
                        }
                        ?>
                    </select>
                </div>
                 <button type="submit" class="btn btn-primary">Add</button>
            </form>
        </div>
    </div>

</div>