<div class="container">
    <?php echo $this->getContent();?>
    <div class="row">
        <div class="col-md-12">
            <form method="post">
                <div class="form-group">
                    <label for="settingValue"><?= $pagesetting->Setting->name; ?></label>
                    <input type="text" class="form-control" name="settingValue" id="settingValue" value="<?= $pagesetting->value; ?>">
                </div>
                 <button type="submit" class="btn btn-primary">Update</button>
            </form>
        </div>
    </div>

</div>