<section class="widgetDataTable">

    <table class="table table-hover listtables" width="100%">
        <thead>
        <tr>
            <th data-priority="1"></th>
            <th data-priority="3"></th>
            <th data-priority="5"></th>
            <th data-priority="4"></th>
            <th data-priority="2"></th>
        </tr>
        </thead>
        <tbody>

        <?php
        foreach ($jsonResponse as $row) {
            ?>
            <tr role="row" class="odd">
                <td tabindex="0"><a href="http://<?= $row[1] ?>" target="_blank"> <?= $row[0] ?></a></td>
                <td><?= $row[2] ?></td>
                <td><?= $row[3] ?></td>
                <td><?= $row[4] ?></td>
                <td>
                    <a href="sendmessage?userName=<?= $row["director"] ?>&amp;toEmail=<?= $row["emailaddress"] ?>&amp;isDirector=true" class="sendMessageIcon"></a>
                </td>
            </tr>
        <?php } ?>

        </tbody>
    </table>

    <script type="text/javascript">
        var oDefault;
        var oSettings;

        $(function () {

            $.fn.dataTableExt.oSort["string-asc"] = function (x, y) {
                return x.toString().localeCompare(y.toString());
            };

            $.fn.dataTableExt.oSort["string-desc"] = function (x, y) {
                return y.toString().localeCompare(x.toString());
            };

            oDefault = {
                "bProcessing": true,
                "responsive": true,
                "bServerSide": false,
                "bLengthChange": false,
                "iDisplayLength": 25,
                "bSort": true,
                "bInfo": true,
                "bPaginate": true,
                "sPaginationType": "full_numbers",
                "aaSorting": [],
				"order": [[0, 'asc']],
                "fnDrawCallback": function (oSettings) {
                    if (oSettings.aiDisplay.length == 0) {
                        return;
                    }

                }
            };

            oSettings = $.extend(true, {}, oDefault);

            oSettings.oLanguage = {
                sLengthMenu: "<?php echo  $this->translator->_('datatablesparameters.sLengthMenu')?>",
                sSearch: "<i class='fa fa-filter' data-toggle='tooltip' title='<?php echo $this->translator->_('cms.v3.admin.editpage.search')?>' aria-hidden='true'></i>",
                sZeroRecords: "<?=$mappedWidgetSettings->getValueByName("Zero Records")?>",
                sEmptyTable: "<?=$mappedWidgetSettings->getValueByName("Zero Records")?>",
                sInfo: "<?=$mappedWidgetSettings->getValueByName("Showing")?> _START_ <?=$mappedWidgetSettings->getValueByName("to")?> _END_ <?=$mappedWidgetSettings->getValueByName("of")?> _TOTAL_ <?=$mappedWidgetSettings->getValueByName("entries")?>",
                sInfoEmpty: "<?=$mappedWidgetSettings->getValueByName("Showing")?> 0 <?=$mappedWidgetSettings->getValueByName("to")?> 0 <?=$mappedWidgetSettings->getValueByName("of")?> 0 <?=$mappedWidgetSettings->getValueByName("entries")?>",
                sInfoFiltered: "",
                oPaginate: {
                    sFirst: "<i class='fa fa-step-backward' aria-hidden='true'></i>",
                    sPrevious: "<i class='fa fa-chevron-left' aria-hidden='true'></i>",
                    sNext: "<i class='fa fa-chevron-right' aria-hidden='true'></i>",
                    sLast: "<i class='fa fa-step-forward' aria-hidden='true'></i>"
                }
            };

            oSettings.aoColumns = [
                {sWidth: "30%", sTitle: "<?=$mappedWidgetSettings->getValueByName("Region Name") ?>"},
                {sWidth: "20%", sTitle: "<?=$mappedWidgetSettings->getValueByName("Location/Area")?>"},
                {sWidth: "20%", sTitle: "<?=$mappedWidgetSettings->getValueByName("Executive Director") ?>"},
                {sWidth: "20%", sTitle: "<?=$mappedWidgetSettings->getValueByName("Telephone Number") ?>"},
                {sWidth: "10%", sTitle: "<?=$mappedWidgetSettings->getValueByName("Send Message") ?>",bSortable: false}
            ];

            $('.listtables').dataTable(oSettings);
			

        });
    </script>
</section>